# Generated by Django 3.2.16 on 2023-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('successful', 'SUCCESSFUL'), ('shipping', 'SHIPPING'), ('cancelled', 'CANCELLED')], default='shipping', max_length=20),
        ),
    ]
